language: php

php:
    - 5.3
    - 5.4
script:
    - ./vendor/bin/phpunit --debug --verbose t/Test
before_install:
    - curl -sS https://getcomposer.org/installer | php
    - composer.phar install --dev
